name: retail_survey_app
description: 零售调研系统 Flutter 版
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 网络请求
  dio: ^5.4.0
  http: ^1.1.0
  http_parser: ^4.0.2
  # 本地存储
  shared_preferences: ^2.2.2
  # 图片选择
  image_picker: ^1.0.7
  # 图片处理
  image: ^4.1.3
  # 路径
  path_provider: ^2.1.1
  # 定位
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  # 日期格式化
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
